module RamlPoliglota
  module Code
    module Builder
      module Java

        class JavaInterfaceModelBuilder

          include RamlPoliglota::Helper::JavaCodeBuilder

          def initialize
            @logger = AppLogger.create_logger self
          end

          def build(clazz)
            return if clazz.nil?

            @logger.debug "Write interface model class #{clazz.namespace}.#{clazz.name}"
            text = ''
            append_package clazz, text
            _write_documentation clazz, text
            _write_class_definition clazz, text

            text << "}"
          end

          private
          def _write_documentation(clazz, target)
            text = []
            text << "/**"
            text << " * Generated by RAML Poliglota."
            text << " *"
            text << " * #{clazz.documentation}"
            text << " */"

            target << write_code(text, 0)
            target << "\n"
          end

          def _write_class_definition(clazz, target)
            definition = ((clazz.is_interface?) ? 'interface' : 'class')
            target << write_code("public #{definition} #{clazz.name} {", 0)
            target << "\n\n"
          end

        end
      end
    end
  end
end