require 'test/unit'
require 'logging'
require File.expand_path '../../../../../assert_helper.rb', __FILE__
require File.expand_path '../../../../../../lib/configuration/app_logger.rb', __FILE__
require File.expand_path '../../../../../../lib/model/class_meta.rb', __FILE__
require File.expand_path '../../../../../../lib/code/builder/java/java_model_builder.rb', __FILE__

class JavaBuilderTest < Test::Unit::TestCase
  
  include RamlPoliglota::Code::Builder::Java
  include RamlPoliglota::Model

  def test_build
    builder = JavaModelBuilder.new
    clazz = _class_object

    expected = _class_text
    actual = builder.build(clazz)
    assert_equal expected, actual
  end

  private
  def _class_object
    ClassMeta.new do |c|
      c.namespace = 'br.mg.gv'
      c.name = 'BilboBaggins'
      c.documentation = 'A Java Bean class.'
      
      c.add_attribute(AttributeMeta.new do |a|
        a.visibility = 'private'
        a.type = 'Integer'
        a.name = 'id'
      end)
      
      c.add_attribute(AttributeMeta.new do |a|
        a.visibility = 'protected'
        a.type = 'String'
        a.name = 'firstName'
      end)
      
      c.add_attribute(AttributeMeta.new do |a|
        a.visibility = 'protected'
        a.type = 'String'
        a.name = 'lastName'
      end)

      c.add_method(MethodMeta.new do |m|
        m.visibility = 'public'
        m.return_type = 'Integer'
        m.name = 'getId'
        m.body = "return this.id;"
      end)

      c.add_method(MethodMeta.new do |m|
        m.visibility = 'public'
        m.return_type = 'String'
        m.name = 'getFirstName'
        m.body = "return this.firstName;"
      end)

      c.add_method(MethodMeta.new do |m|
        m.visibility = 'public'
        m.return_type = 'String'
        m.name = 'getLastName'
        m.body = "return this.lastName;"
      end)

      c.add_method(MethodMeta.new do |m|
        m.visibility = 'public'
        m.return_type = 'void'
        m.name = 'setId'
        m.parameters = [AttributeMeta.new { |a| a.name = 'id'; a.type = 'Integer' }]
        m.body = "this.id = id;"
      end)

      c.add_method(MethodMeta.new do |m|
        m.visibility = 'public'
        m.return_type = 'void'
        m.name = 'setFirstName'
        m.parameters = [AttributeMeta.new { |a| a.name = 'firstName'; a.type = 'String' }]
        m.body = "this.firstName = firstName;"
      end)

      c.add_method(MethodMeta.new do |m|
        m.visibility = 'public'
        m.return_type = 'void'
        m.name = 'setLastName'
        m.parameters = [AttributeMeta.new { |a| a.name = 'lastName'; a.type = 'String' }]
        m.body = "this.lastName = lastName;"
      end)

      c.add_method(MethodMeta.new do |m|
        m.visibility = 'public'
        m.return_type = 'BilboBaggins'
        m.name = 'withId'
        m.parameters = [AttributeMeta.new { |a| a.name = 'id'; a.type = 'Integer' }]
        m.body = "this.id = id;\nreturn this;"
      end)

      c.add_method(MethodMeta.new do |m|
        m.visibility = 'public'
        m.return_type = 'BilboBaggins'
        m.name = 'withFirstName'
        m.parameters = [AttributeMeta.new { |a| a.name = 'firstName'; a.type = 'String' }]
        m.body = "this.firstName = firstName;\nreturn this;"
      end)

      c.add_method(MethodMeta.new do |m|
        m.visibility = 'public'
        m.return_type = 'BilboBaggins'
        m.name = 'withLastName'
        m.parameters = [AttributeMeta.new { |a| a.name = 'lastName'; a.type = 'String' }]
        m.body = "this.lastName = lastName;\nreturn this;"
      end)
    end
  end

  def _class_text
    text = <<-FIN
package br.mg.gv;

/**
 * Generated by RAML Poliglota
 * A Java Bean class.
 */

public class BilboBaggins {

  private Integer id;
  protected String firstName;
  protected String lastName;

  public Integer getId() {
    return this.id;
  }

  public String getFirstName() {
    return this.firstName;
  }

  public String getLastName() {
    return this.lastName;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public BilboBaggins withId(Integer id) {
    this.id = id;
    return this;
  }

  public BilboBaggins withFirstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

  public BilboBaggins withLastName(String lastName) {
    this.lastName = lastName;
    return this;
  }
}
FIN
    text.rstrip
  end

end