require 'test/unit'
require 'logging'
require File.expand_path '../../../../../assert_helper.rb', __FILE__
require File.expand_path '../../../../../../lib/configuration/app_logger.rb', __FILE__
require File.expand_path '../../../../../../lib/model/class_meta.rb', __FILE__
require File.expand_path '../../../../../../lib/code/builder/java/java_model_builder.rb', __FILE__

class JavaBuilderTest < Test::Unit::TestCase
  
  include RamlPoliglota::Code::Builder::Java
  include RamlPoliglota::Model

  def test_build
    builder = JavaModelBuilder.new

    clazz = ClassMeta.new do |c|
      c.namespace = 'br.mg.gv'
      c.name = 'BilboBaggins'
      c.documentation = 'A Java Bean class.'
    end

    expected = <<-FIN
package br.mg.gv;

/**
 * Generated by RAML Poliglota
 * A Java Bean class.
 */

public class BilboBaggins {

}
FIN
    expected.rstrip!
    actual = builder.build(clazz)
    assert_equal expected, actual
  end

end