require 'test/unit'
require 'logging'
require File.expand_path '../../../../../assert_helper.rb', __FILE__
require File.expand_path '../../../../../../lib/configuration/app_logger.rb', __FILE__
require File.expand_path '../../../../../../lib/model/class_meta.rb', __FILE__
require File.expand_path '../../../../../../lib/code/builder/java/java_model_builder.rb', __FILE__

class JavaBuilderTest < Test::Unit::TestCase
  
  include RamlPoliglota::Code::Builder::Java
  include RamlPoliglota::Model

  def test_build
    builder = JavaModelBuilder.new

    clazz = ClassMeta.new do |c|
      c.namespace = 'br.mg.gv'
      c.name = 'BilboBaggins'
      c.documentation = 'A Java Bean class.'
      
      c.add_attribute(AttributeMeta.new do |a|
        a.visibility = 'private'
        a.type = 'Integer'
        a.name = 'id'
      end)
      
      c.add_attribute(AttributeMeta.new do |a|
        a.visibility = 'protected'
        a.type = 'String'
        a.name = 'firstName'
      end)
      
      c.add_attribute(AttributeMeta.new do |a|
        a.visibility = 'protected'
        a.type = 'String'
        a.name = 'lastName'
      end)
    end

    puts " >>> #{clazz.attributes.size}"

    expected = <<-FIN
package br.mg.gv;

/**
 * Generated by RAML Poliglota
 * A Java Bean class.
 */

public class BilboBaggins {

  private Integer id;
  protected String firstName;
  protected String lastName;
}
FIN
    expected.rstrip!
    actual = builder.build(clazz)
    assert_equal expected, actual
  end

end